import { type Scope } from '../paths.js';
import { writeKnowledgeFile, removeWikiEntry, listWikiEntries, readWikiFile } from '../store/index.js';
import { listKnowledgePages } from './pages.js';
import { posixBase, posixDir } from './frontmatter.js';
import type { KnowledgePage } from './pages.js';

// 一份重算出的 index.md(路径相对 knowledge/)
export interface KnowledgeIndexFile {
  // 相对 knowledge/ 的路径(如 "index.md"、"wiki/backend/index.md")
  path: string;

  // 渲染后的 markdown 正文
  content: string;
}

const GENERATED_MARKER = '<!-- Generated by `withy knowledge index`. Do not edit by hand. -->';

// 根 catalog 的分组表头(按显示顺序);未知 kind 退化为原名,无 kind 归入 Other
const KIND_GROUPS: ReadonlyArray<readonly [string, string]> = [
  ['spec', 'Specs'],
  ['overview', 'Overviews'],
  ['concept', 'Concepts'],
  ['entity', 'Entities'],
  ['comparison', 'Comparisons'],
  ['summary', 'Summaries'],
  ['template', 'Templates'],
  ['log', 'Logs'],
];

// index.md 是生成物,永不接受单独 save/rename/delete。
export function isIndexFile(relPath: string): boolean {
  return posixBase(relPath) === 'index.md';
}

function byTitle(a: KnowledgePage, b: KnowledgePage): number {
  return a.title.localeCompare(b.title);
}

function pageRow(page: KnowledgePage, href: string): string {
  return page.summary ? `- [${page.title}](${href}) — ${page.summary}` : `- [${page.title}](${href})`;
}

// 每个非根目录路径 → 其子树下页数(子目录链接的一行描述)
function subtreeCounts(pages: KnowledgePage[]): Map<string, number> {
  const counts = new Map<string, number>();
  for (const page of pages) {
    const dir = posixDir(page.wikiRelPath);
    if (!dir) continue;

    let prefix = '';
    for (const segment of dir.split('/')) {
      prefix = prefix ? `${prefix}/${segment}` : segment;
      counts.set(prefix, (counts.get(prefix) ?? 0) + 1);
    }
  }

  return counts;
}

function renderGroupedSections(lines: string[], pages: KnowledgePage[], href: (page: KnowledgePage) => string): void {
  if (!pages.length) return;

  const byKind = new Map<string, KnowledgePage[]>();
  for (const page of pages) {
    const key = page.kind ?? '';
    const list = byKind.get(key);
    if (list) list.push(page);
    else byKind.set(key, [page]);
  }

  const known = new Set(KIND_GROUPS.map(([kind]) => kind));
  const order: Array<readonly [string, string]> = [...KIND_GROUPS];
  for (const kind of [...byKind.keys()].filter(key => key && !known.has(key)).sort()) {
    order.push([kind, `${kind[0].toUpperCase()}${kind.slice(1)}`]);
  }
  if (byKind.has('')) order.push(['', 'Other']);

  for (const [kind, label] of order) {
    const group = byKind.get(kind);
    if (!group?.length) continue;
    lines.push(`## ${label}`, '');
    for (const page of [...group].sort(byTitle)) lines.push(pageRow(page, href(page)));
    lines.push('');
  }
}

function renderFlatPages(lines: string[], pages: KnowledgePage[], href: (page: KnowledgePage) => string): void {
  if (!pages.length) return;
  for (const page of [...pages].sort(byTitle)) lines.push(pageRow(page, href(page)));
  lines.push('');
}

function renderSubdirs(lines: string[], subdirs: Set<string>, link: (name: string) => [string, number]): void {
  if (!subdirs.size) return;

  lines.push('## Subdirectories', '');
  for (const name of [...subdirs].sort()) {
    const [href, count] = link(name);
    lines.push(`- [${name}/](${href}) — ${count} ${count === 1 ? 'entry' : 'entries'}`);
  }
  lines.push('');
}

/**
 * 据各页 frontmatter 确定性重算各级 index.md 内容(纯函数,不碰盘)。
 * 根索引(knowledge/index.md)按 kind 分组列 wiki/ 顶层页 + 链向各子目录;
 * 子目录索引(wiki/<topic>/index.md)平铺列直接子项。
 *
 * @param pages 维护视图页清单
 * @return 每级一份 index.md(路径相对 knowledge/);wiki 为空也产一份根目录索引
 */
export function buildKnowledgeIndexes(pages: KnowledgePage[]): KnowledgeIndexFile[] {
  interface DirNode {
    pages: KnowledgePage[];
    subdirs: Set<string>;
  }
  const dirs = new Map<string, DirNode>();
  const ensure = (key: string): DirNode => {
    let node = dirs.get(key);
    if (!node) {
      node = { pages: [], subdirs: new Set() };
      dirs.set(key, node);
    }
    return node;
  };

  ensure(''); // always emit a root catalog, even for an empty wiki

  for (const page of pages) {
    const dir = posixDir(page.wikiRelPath);
    ensure(dir).pages.push(page);

    let prefix = '';
    for (const segment of dir ? dir.split('/') : []) {
      ensure(prefix).subdirs.add(segment);
      prefix = prefix ? `${prefix}/${segment}` : segment;
      ensure(prefix);
    }
  }

  const counts = subtreeCounts(pages);
  const files: KnowledgeIndexFile[] = [];
  for (const [dir, node] of dirs) {
    files.push({
      path: dir ? `wiki/${dir}/index.md` : 'index.md',
      content: dir
        ? renderSubdirIndex(dir, node.pages, node.subdirs, counts)
        : renderRootIndex(node.pages, node.subdirs, counts),
    });
  }

  return files;
}

function renderRootIndex(pages: KnowledgePage[], subdirs: Set<string>, counts: Map<string, number>): string {
  const lines = [GENERATED_MARKER, '', '# Knowledge', ''];
  renderGroupedSections(lines, pages, page => `wiki/${page.wikiRelPath}`);
  renderSubdirs(lines, subdirs, name => [`wiki/${name}/`, counts.get(name) ?? 0]);

  return `${lines.join('\n').trimEnd()}\n`;
}

function renderSubdirIndex(
  dir: string,
  pages: KnowledgePage[],
  subdirs: Set<string>,
  counts: Map<string, number>,
): string {
  const lines = [GENERATED_MARKER, '', `# ${posixBase(dir)}/`, ''];
  renderFlatPages(lines, pages, page => posixBase(page.wikiRelPath));
  renderSubdirs(lines, subdirs, name => [`${name}/`, counts.get(`${dir}/${name}`) ?? 0]);

  return `${lines.join('\n').trimEnd()}\n`;
}

/**
 * 重算并写回某 scope 各级 index.md(确定性 bookkeeping)。
 *
 * @param scope 目标 scope
 * @return 写出的索引文件清单(含正文)
 */
export function rebuildKnowledgeIndexes(scope: Scope): KnowledgeIndexFile[] {
  const indexes = buildKnowledgeIndexes(listKnowledgePages(scope));
  for (const file of indexes) writeKnowledgeFile(scope, file.path, file.content);

  return indexes;
}

/**
 * 结构性写后统一调用:先 `rebuildKnowledgeIndexes` 写出当前应有的各级 index.md,
 * 再扫 wiki/ 下首行带 `GENERATED_MARKER` 但不在应有集合中的 `index.md` 删除
 * (只删自己生成的,不误伤手写)。封装在写函数内,不改 `rebuildKnowledgeIndexes` 对外契约。
 */
export function rebuildAndCleanIndexes(scope: Scope): void {
  const expected = new Set(rebuildKnowledgeIndexes(scope).map(file => file.path));

  for (const entry of listWikiEntries(scope)) {
    if (entry.type !== 'file' || !isIndexFile(entry.relPath)) continue;
    if (expected.has(`wiki/${entry.relPath}`)) continue;

    const raw = readWikiFile(scope, entry.relPath);
    if (raw && raw.startsWith(GENERATED_MARKER)) removeWikiEntry(scope, entry.relPath);
  }
}
